# This file specifies configuration for ESLint.

---
  root: true
  parser: "@typescript-eslint/parser"
  parserOptions:
    project: "./tsconfig.eslint.json"
  plugins:
    - "@typescript-eslint"
  extends:
    - eslint:recommended
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended"
  rules:
    no-var: error
    "@typescript-eslint/no-var-requires": off
    indent: ["error", 2]
    eqeqeq: error
    no-unexpected-multiline: error
    no-constant-condition: off
    "@typescript-eslint/member-delimiter-style":
      - error
      - 
        singleline:
          delimiter: "comma"
          requireLast: false
        multiline:
          delimiter: "comma"
          requireLast: true
    "@typescript-eslint/interface-name-prefix":
      - warn
    "@typescript-eslint/no-empty-interface": off
    "@typescript-eslint/no-empty-function": off
    "@typescript-eslint/no-floating-promises":
      - error
      - 
        ignoreVoid: true
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-this-alias":
      - error
      -
        allowDestructuring: true
        allowedNames: ['that']
  env:
    node: true
